### PR TITLE
Update macports version to 2.10.0

### PR DESCRIPTION
**Pull request by jhoyt4**
Upgrades script to the latest macports version (2.10.0).

### CODE REVIEW

**Comment by GiovanniBussi** [comment]
@jhoyt4 thanks for this PR!

A couple of questions:
- how did you test macos-15? I could not find how to set it up in a GitHub runner.
- I just tried to have the 2.10.0 update to work, but I see [some failures](https://github.com/GiovanniBussi/macports-ci/actions/runs/10340812469). I see also failures on the [master branch now (with MP 2.9.3)](https://github.com/GiovanniBussi/macports-ci/actions/runs/10340852401). Did you test the proposed modification on GitHub Actions?

**Comment by jhoyt4** [comment]
> * how did you test macos-15? I could not find how to set it up in a GitHub runner.

I did not - was just prepping for when the runner became available.  I can back that out

> * I just tried to have the 2.10.0 update to work, but I see [some failures](https://github.com/GiovanniBussi/macports-ci/actions/runs/10340812469). I see also failures on the [master branch now (with MP 2.9.3)](https://github.com/GiovanniBussi/macports-ci/actions/runs/10340852401). Did you test the proposed modification on GitHub Actions?

I did test, got through the macports install and installation of most ports:
https://github.com/MythTVforMacOS/compileMythTV/actions/runs/10340618493

The issues I'm seeing the Build Log are issues with the mysql8 port (which I had before testing in last nights weekly build) and code signing, but macports 2.10.0 was working off my fork.

**Comment by jhoyt4** [comment]
I just backed out the Sequoia lines.

I believe macports might be having issues.  It may be worth waiting for some of those to settle out and see what's really related.

**Comment by jhoyt4** [comment]
I jacked up my branch, happy to let you fix on your side.

**Pull request closed without merging**
